spring:
  application:
    name: postPI

  datasource:
    url: jdbc:postgresql://localhost:5432/control_plane
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public

server:
  port: 8080

app:
  jwt:
    secret: "change-this-to-a-long-random-string-at-least-32-characters-for-hs256"
    expiration-ms: 86400000

  rate-limit:
    max-requests: 100
    window-seconds: 60